# Site settings
title: Arash Arjmandi
author: Arash Arjmandi
description: This website is a place to share my projects, ideas, and contact information.
url: "https://arash.arjmandi.nl"
linkedin_username: arash-arjmandi

# Build settings
theme: minima
markdown: kramdown
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
