# Site settings
title: My Personal Page
author: Arash Arjmandi
description: This website is a place to share my projects, ideas, and contact information.
linkedin_username: arash-arjmandi
substack_url: "https://substack.com/@learningbits"
substack_title: Learning Bits

# Build settings
theme: minima
markdown: kramdown
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
