# Site settings
title: My Personal Page
description: Arash Arjmandi. This website contains information about my projects, and contact information.

# Build settings
theme: minima
markdown: kramdown
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

minima:
  
  social_links:
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/arash-arjmandi" }
    - { platform: substack, user_url: "https://substack.com/@learningbits",  user_title: "Learning Bits"}